export enum UserRole {
  ADMIN,
  EMPLOYEE,
  APPLICANT,
}

export enum TaskType {
  PROG_TASK,
  TEST_QUESTION
}

export enum TaskResult {
  DONE,
  FAIL,
  FAIL_TIME,
  FAIL_MEMORY
}

export enum Vacancy {
  JAVA_JUNIOR = 'JAVA_JUNIOR',
  JAVA_MIDDLE = 'JAVA_MIDDLE',
  JAVA_SENIOR = 'JAVA_SENIOR',
  JS_FRONTEND_JUNIOR = 'JS_FRONTEND_JUNIOR',
  JS_FRONTEND_MIDDLE = 'JS_FRONTEND_MIDDLE',
  JS_FRONTEND_SENIOR = 'JS_FRONTEND_SENIOR',
  JS_BACKEND_JUNIOR = 'JS_BACKEND_JUNIOR',
  JS_BACKEND_MIDDLE = 'JS_BACKEND_MIDDLE',
  JS_BACKEND_SENIOR = 'JS_BACKEND_SENIOR',
  JS_FULLSTACK_JUNIOR = 'JS_FULLSTACK_JUNIOR',
  JS_FULLSTACK_MIDDLE = 'JS_FULLSTACK_MIDDLE',
  JS_FULLSTACK_SENIOR = 'JS_FULLSTACK_SENIOR',
}

export enum ProgrammingLanguage {
  Java = 'java',
  JavaScript = 'javascript'
}